apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
        - name: chat-app-backend
          image: ayushayush/chat-app-backend
          resources:
            requests:
              memory: "128Mi"
              cpu: "256m"
            limits:
              memory: "256Mi"
              cpu: "512m"
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: backend_port
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: node_env
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongo_uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-app-secret
                  key: jwt
